<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MBtecZfSuperMessenger\View\Helper\Service\SuperMessengerFactory' => __DIR__ . '/src/SuperMessenger/View/Helper/Service/SuperMessengerFactory.php',
  'MBtecZfSuperMessenger\View\Helper\SuperMessenger'                => __DIR__ . '/src/SuperMessenger/View/Helper/SuperMessenger.php',
  'MBtecZfSuperMessenger\Module'                                    => __DIR__ . '/Module.php',
);
